pr:
  - master
  - feature/*
  - epic/*

trigger:
  batch: true
  branches:
    include:
      - master
      - feature/*
    exclude:
      - test/*
      - temp/*
  paths:
    exclude:
      - docs/*
      - README.md
jobs:
  - job: SastScans
    displayName: "Run SAST scan"
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - script: docker pull quay.io/appthreat/sast-scan
      - script: |
          docker run -e "WORKSPACE=https://github.com/AppThreat/insecure-sample-projects/blob/$(Build.SourceVersion)" \
            -e "REPOSITORY_URL=$(Build.Repository.Uri)" \
            -e "COMMIT_SHA=$(Build.SourceVersion)" \
            -e "BRANCH=$(Build.SourceBranch)" \
            -v $(Build.SourcesDirectory):/app \
            -v $(Build.ArtifactStagingDirectory):/reports \
            quay.io/appthreat/sast-scan scan --src /app \
            --type credscan,python,nodejs \
            --out_dir /reports/CodeAnalysisLogs
        displayName: "Python and Nodejs"
        continueOnError: "true"      
      - task: PublishBuildArtifacts@1
        displayName: "Publish analysis logs"
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/CodeAnalysisLogs'
          ArtifactName: 'CodeAnalysisLogs'
          publishLocation: 'Container'
          
